name: floating_menu_panel
description: Floating menu panel
version: 0.0.2
homepage: https://github.com/GioRey/floating_menu_panel

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
